import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Max Ovsiankin',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-transparent sticky backdrop-blur-md top-0 right-0 left-0 border-b border-slate-200 z-50">
        <div className="max-w-4xl px-4 m-auto flex">
          <div className="font-bold py-5">
            <Link href="/" className="transition hover:text-gray-600">Home</Link>
          </div>
          <div className="flex-grow"></div>
          <div className="font-bold py-5">
            <Link href="/blog/" className="mr-8 transition hover:text-gray-600">Blog</Link>
            <Link href="/cv/" className="transition hover:text-gray-600">CV</Link>
          </div>
        </div> 
      </header>
        {children}
      </body>
    </html>
  )
}
